# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alessio R Loreti
email: alessiorloreti@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Atlanta Based Photographer, Traveler, and Adventurer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alessiorloreti.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

# Google services
google_analytics: UAâ€”102761465-1
